[project]
name = "eavesdrop-client"
version = "0.0.0"
description = "Python client library for Eavesdrop real-time transcription services"
readme = "README.md"
authors = [{name = "shyndman", email = "scotty.hyndman@gmail.com"}]
requires-python = ">=3.12"
dependencies = [
    "eavesdrop-wire",
    "numpy<2",
    "pydantic>=2",
    "sounddevice>=0.5.2",
    "structlog>=25.4.0",
    "websockets>=13.0",
]

[project.scripts]
eavesdrop = "eavesdrop.client.__main__:main"

[project.urls]
repository = "https://github.com/shyndman/eavesdrop"
"Bug Tracker" = "https://github.com/shyndman/eavesdrop/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/eavesdrop"]

[tool.uv.sources]
eavesdrop-wire = {path = "../wire", editable = true}

[tool.pyright]
include = ["src"]
ignore = ["**/.venv"]
defineConstant = {DEBUG = true}
reportMissingImports = "error"
deprecateTypingAliases = true
reportDeprecated = "information"
pythonPlatform = "Linux"

[tool.ruff]
line-length = 100
target-version = "py312"
indent-width = 2

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["eavesdrop"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
