repos:
  - repo: https://github.com/shyndman/unroot-llm-files-pre-commit
    rev: v0.0.8
    hooks:
      - id: setup-managed-symlinks
      - id: check-managed-symlinks
      - id: update-gitignore-for-symlinks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.4
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd packages/active-listener-ui-electron && pnpm run lint"
        language: node
      - id: prettier
        name: prettier
        entry: bash -c "cd packages/active-listener-ui-electron && pnpm run format"
        language: node
