[project]
name = "eavesdrop-server"
version = "0.0.0"
description = "Real-time audio transcription server with WebSocket-based speech-to-text services"
authors = [{name = "shyndman", email = "scotty.hyndman@gmail.com"}]
requires-python = ">=3.12"
dependencies = [
  "eavesdrop-common",
  "eavesdrop-wire",
  "evaluate",
  "jiwer",
  "kaldialign",
  "netifaces>=0.11.0",
  "numba",
  "numpy<2",
  "psutil",
  "pydantic>=2",
  "pyyaml>=6.0",
  "sentencepiece",
  "soundfile",
  "structlog>=25.4.0",
  "websocket-client>=1.8.0",
  "websockets",
  # These are installed via other means (see Dockerfile)
  # "tokenizers==0.20.3",
  # "transformers[torch]==4.54",
  # "faster-whisper==1.1.1",
  # "openai-whisper==20240930",
  # "ctranslate2 @ file:///~/dev/github.com/ctranslate2",
]
license = {text = "MIT"}


[project.urls]
repository = "https://github.com/shyndman/eavesdrop"
"Bug Tracker" = "https://github.com/shyndman/eavesdrop/issues"

[project.scripts]
eavesdrop-server = "eavesdrop.server.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/eavesdrop"]

[dependency-groups]
dev = ["pyfakefs>=5.9.3", "pytest>=8.3.5"]
type_checkable = [
  "torch==2.6.0",
  "torchaudio==2.6.0",
  "faster-whisper==1.1.0",
  "pytorch-triton-rocm==3.2.0",
]

[tool.pyright]
include = ["src", "tests"]
ignore = ["**/.venv"]
defineConstant = {DEBUG = true}
reportMissingImports = "error"
deprecateTypingAliases = true
reportDeprecated = "information"
pythonPlatform = "Linux"

[tool.ruff]
line-length = 100
target-version = "py312"
indent-width = 2

[tool.ruff.lint.flake8-tidy-imports]
# Disallow all relative imports.
ban-relative-imports = "all"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["eavesdrop"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.uv.sources]
eavesdrop-wire = {path = "../wire", editable = true}
torch = {index = "pytorch"}
torchaudio = {index = "pytorch"}
pytorch-triton-rocm = {index = "pytorch"}
eavesdrop-common = { path = "../common", editable = true }

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/rocm6.2.4"
explicit = true
